import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header style={{background:'#07111b',borderBottom:'1px solid #123',padding:'10px 18px',zIndex:90}}>
          <div style={{maxWidth:1200,margin:'0 auto',display:'flex',alignItems:'center',justifyContent:'space-between'}}>
            <a href="/home" style={{color:'#eaf5ff',fontWeight:900,textDecoration:'none',fontSize:18}}>GameBattles</a>
            <nav style={{display:'flex',gap:14}}>
              <a href="/home" style={{color:'#cfeefe',textDecoration:'none'}}>Home</a>
              <a href="/forums" style={{color:'#cfeefe',textDecoration:'none'}}>Forums</a>
              <a href="/teams/top" style={{color:'#cfeefe',textDecoration:'none'}}>Teams</a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
